create index payroll_runs_generated_by_idx
on public.payroll_runs (generated_by);
create index payroll_runs_approved_by_idx
on public.payroll_runs (approved_by);
create index payroll_workers_primary_project_idx
on public.payroll_workers (primary_project_id);
create index payroll_buckets_rate_period_idx
on public.payroll_earning_buckets (rate_period_id);
create index payroll_exceptions_project_idx
on public.payroll_exceptions (project_id);
create index payroll_adjustments_worker_idx
on public.payroll_adjustments (worker_id);
create index payroll_adjustments_created_by_idx
on public.payroll_adjustments (created_by);
create index payroll_revisions_approved_by_idx
on public.payroll_approval_revisions (approved_by);
create index payroll_statements_generated_by_idx
on public.payroll_statements (generated_by);
create index payroll_payments_paid_by_idx
on public.payroll_payments (paid_by);
